// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CommentController from "./comment_controller"
application.register("comment", CommentController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InvitationsController from "./invitations_controller"
application.register("invitations", InvitationsController)

import LikeController from "./like_controller"
application.register("like", LikeController)

import LogoutController from "./logout_controller"
application.register("logout", LogoutController)

import PostPromptController from "./post_prompt_controller"
application.register("post-prompt", PostPromptController)

import SearchFormController from "./search_form_controller"
application.register("search-form", SearchFormController)
